version: '3'
services:
  db:
    hostname: db
    image: mysql:8.0.23
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  ms-article-1:
    image: rouvsen/ms_article1:1.0.4e4096c
    restart: always
    environment:
      - DB_CONNECTION_USERNAME=root
      - DB_CONNECTION_PASSWORD=password
      - DB_CONNECTION_IP=db
      - DB_CONNECTION_PORT=3306
#      - KAFKA_BROKER_HOST_NAME=kafka
#      - KAFKA_BROKER_PORT=9091
    ports:
      - "8081:8081"
    depends_on:
      - db
#      - "kafka"
  ms-article-2:
    image: rouvsen/ms_article2:1.0.4e4096c
    restart: always
    environment:
      - DB_CONNECTION_USERNAME=root
      - DB_CONNECTION_PASSWORD=password
      - DB_CONNECTION_IP=db
      - DB_CONNECTION_PORT=3306
#      - KAFKA_BROKER_HOST_NAME=kafka
#      - KAFKA_BROKER_PORT=9091
    ports:
      - "8082:8082"
    depends_on:
      - db
#      - "kafka"
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    ports:
      - 8580:8080
  reverse_proxy:
    image: nginx:latest
    hostname: proxy
    container_name: reverse_proxy
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ms-article-1
      - ms-article-2
#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    restart: "no"
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BROKERCONNECT: "kafka:29092"
#      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
#    depends_on:
#      - "kafka"
#  kafka:
#    image: obsidiandynamics/kafka
#    restart: "no"
#    ports:
#      - "2181:2181"
#      - "9092:9092"
#    environment:
#      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
#      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
#      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
#      KAFKA_RESTART_ATTEMPTS: "10"
#      KAFKA_RESTART_DELAY: "5"
#      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

volumes:
  db_data:
#  elasticsearch_data2:
  nginx:
#  mongodb_data: